title: Jesse Lansdown
email: 
description: # > # this means to ignore newlines until "baseurl:"
Research Associate in the Centre for the Mathematics of Symmetry and Computation, the University of Western Australia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  

# Build settings
#markdown: kramdown
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
